.TH BNM3 1 "January 2026" "0.7.0" "BoredNoMore3 Manual"
.SH NAME
bnm3 \- Legacy GUI for BoredNoMore3 wallpaper manager
.SH SYNOPSIS
.B bnm3
.SH DESCRIPTION
.B bnm3
is the original graphical user interface for the BoredNoMore3 suite. It allows users to browse and set wallpapers via a simple GTK/Tk interface.
.SH SEE ALSO
bnm3d-gui(1), borednomore3(1)
