#!/bin/sh
set -e

case "$1" in
    purge)
        echo "Removing BoredNoMore3 data and configurations..."
        rm -rf /etc/borednomore3
        rm -rf /usr/lib/borednomore3
        rm -rf /usr/share/borednomore3
    ;;

    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
